### ISSUE TITLE
Possibility to disable Volume-Control

### ISSUE THREAD

**Issue by wagner-ch** [aesculus/denonavpcontrol#11]
I have a Denon CEOL receiver, and it works to some extend with this plugin, but volume synchronisation/volume control doesn't seem to work. I tried a lot of different "max values" for Volume, but any setting has almost the same effect. If I change volume of squeezebox, volume of receiver goes to max. 

Therefor I'd like to have an option to totally disable this feature and just use this plugin for turning the receiver on or off.

**Comment by wagner-ch** [comment]
Further explanation
The commands to set volume via telnet on Denon CEOL are:
Check volume: `MV?`
Volume 0: `MV0`
Volume max: `MV60`
The squeezebox is connected to CEOL via Digitial Input, so my current setting is, that squeezebox is always set to 100% volume, volume control itself is still done with denon remote control.

**Comment by aesculus** [comment]
On the older Denon's that this was designed for setting volume to 100% works just fine. The SB sends the instructions to the plugin and it then sends the command to the Denon.

You will need to get the CEOL API instructions and see what the appropriate commands are. Then you can adapt the plugin to your system.

Or you can just take the source and comment out the volume requests if you want a simple fix like you stated.

**Comment by aesculus** [comment]
This might be fixed in version 2.1.
