### ISSUE TITLE
Possibility to select input source on turning receiver on

### ISSUE THREAD

**Issue by wagner-ch** [aesculus/denonavpcontrol#12]
I have a Denon CEOL that works to some extend with this plugin. However, there is no QuickSelect functionality in protocol. But there is a possibility to select input source.

I can select e.g. "Digital In 1"  by sending 

`SIDIGITALIN1` to telnet protocol. 

Or I can check selected input by sending

`SI?`

Is there a possibility to implement a parameter that I can enter and so select input source on turning receiver on (equivalent to current supported "Quick select" functionality)?

**Comment by aesculus** [comment]
You will have to take this on yourself. First you will need to find (if available) the API command set for what you want to do.  You should then be able to substitute the commands your need from the normal Denon internet prototocol.

**Comment by bjarteskogoy** [comment]
@wagner-ch and @aesculus is there a main repo or way to distribute updates? Could the input select be included as a PR?

**Comment by aesculus** [comment]
The updates are embedded into LMS Plugins panel.

You can manually update them from here too.

I'll look at the input select as a future feature.
