### ISSUE TITLE
LMS Docker Install and DenonAVPControl

### ISSUE THREAD

**Issue by tboneco** [aesculus/denonavpcontrol#18]
I've been using Denonavpcontrol for a while and really depend on the application.  It's AWESOME!  Unfortunately, I am trying to move to Docker install for LMS due to Synology dropping LMS as a supported application.  I have everything up and running via docker and can install various plug-ins but I cannot get Denonavpcontrol to install.  It shows in 3rd party list, I can check it, I receive server prompt to restart, but it does not install.  I am seeing this error:

Slim::Utils::PluginDownloader::_downloadError (266) unable to download DenonAvpControl from https://github.com/aesculus/denonavpcontrol/raw/master/DenonAvpControl_4_5_1.zip - 404 Not Found

**Comment by SamInPgh** [comment]
Please hold on and try again later. We are in the midst of rolling out version 4.6, and experiencing some problems getting it updated in the LMS plugin repository. Sorry for the inconvenience.

**Comment by aesculus** [comment]
Version 4.6 should be available now or soon. It showed up on my system and installed OK.

**Comment by tboneco** [comment]
Yes, all working for me!  Thanks
