### ISSUE TITLE
Possibility to select source instead of quick select?

### ISSUE THREAD

**Issue by bjarteskogoy** [aesculus/denonavpcontrol#22]
I would really appreciate it, if it could be possible to either select a source or a quick select. One of my receivers does not have quick select, and it is used for a lot of things.

**Comment by SamInPgh** [comment]
This feature has been requested before but was a low priority due to the amount of coding effort needed to implement it. However, now that the ability to switch source inputs has been added to the audio settings menu, it is a much simpler matter. This should be available in the next release.

**Comment by SamInPgh** [comment]
Coding completed and tested. Will be included in v4.6.3.

**Comment by SamInPgh** [comment]
Fixed in v4.6.3.
