### ISSUE TITLE
DENON AVR 1912 Unknown Model

### ISSUE THREAD

**Issue by GhettoFuzhun** [aesculus/denonavpcontrol#24]
I am trying to get this plugin working with my network capable denon receiver.  It is a Denon AVR 1912.  When I go into the Denon/Marantz AVR Settings page, it shows "model: unknown".

The volume controls don't synchronize with Squeezer.  When I start a random mix, it will load a playlist, then I have to click play to start it.  After the first song is done, the player will hang, with the playback timer usually reading more than the number of seconds in the song.  I'm not sure if my model is not supported or there is a config issue.  The receiver is visible on my network with a static IP.

**Comment by aesculus** [comment]
Can you post a log of the plugin when when you start LMS? You will need to turn logging (debug) on in the settings?plugin before you restart LMS and then pull the log and post after it starts and you try to turn on the device you are using the plugin with. And I assume you followed the instructions on putting in your IP address etc in the settings for the device via the LMS settings menu.

**Comment by GhettoFuzhun** [comment]
I manually set the IP address and subnet and everything seems to be working properly now.

**Comment by GhettoFuzhun** [comment]
I manually set the IP address and subnet and everything appears to be working now.
